default_platform(:ios)

platform :ios do
    desc "Unit tests"
    lane :tests do
          run_tests(
            scheme: "PerformanceTest"
        )
                
        error do |ex|
          slack(message: "Tests have failed!",
          channel: "#performance")
        end
    end
end
