name: Pull Request
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-12

    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120

    steps:
      - uses: actions/checkout@v2

      - uses: styfle/cancel-workflow-action@0.9.1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1

      - run: gem install bundler

      - run: bundle install

      - name: Cache SPM packages
        uses: actions/cache@v3
        id: cache-spm
        with:
            path: .build
            key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
            restore-keys: |
               ${{ runner.os }}-spm-

      #- name: Run Tests (No SPM Cache)
      #  if: steps.setup.outputs.cache-hit != 'true'
      #  run: bundle exec fastlane tests
      
      - name: Run Tests (Using SPM Cache)
        if: steps.setup.outputs.cache-hit == 'true'
        run: bundle exec fastlane tests skip_package_dependencies_resolution:true

      - name: Run Tests (No SPM Cache)
        run: bundle exec fastlane tests

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: fastlane/report.xml

      - name: Save test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: fastlane/test_output/report.html
          retention-days: 365