name: Pull Request
on:
  pull_request:
    branches [ main ]

jobs:
  test:
    runs-on: macos-12

    env:
      ME_GITHUB_NAME: Builder Bot
      ME_GITHUB_EMAIL: tech+githubbuilder@aibetic.com
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120

    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

       - name Run Tests
        run: bundle exec fastlane tests